#!/usr/bin/env python3
"""Manifest copy for the .project/ durable-state sync (see skills/shared/STATE-SYNC.md).

Single source of truth for WHICH files travel on the `claude/state` orphan branch.
Include-list based: anything not explicitly listed is never copied. A hard denylist
is enforced in both directions as defense-in-depth (even against a tampered state
branch), so credentials (auth-state.json) and regenerable/ephemeral artifacts never
leak onto the branch or get restored.

Usage:
  state-files.py collect --project <dir> --dest <dir>
      Copy the manifest subset of <dir>/.project/ into <dest> (branch-root layout
      mirrors .project/-relative paths). Also writes <dest>/state-manifest.json.

  state-files.py restore --src <dir> --project <dir>
      Inverse copy from <src> into <dir>/.project/, creating dirs. Restores only the
      manifest subset (same include-list as collect) — anything else on the branch,
      including a tampered credential or report, is dropped.

Cross-platform: pure stdlib. On Windows invoke via `python` if `python3` is absent.
"""
from __future__ import annotations

import argparse
import json
import shutil
import socket
import sys
from datetime import datetime, timezone
from fnmatch import fnmatch
from pathlib import Path

# --- Manifest (include-list) -------------------------------------------------

# Top-level .project/ files. architecture.mmd is optional (copied only if present).
TOP_LEVEL_FILES = [
    "project.json",
    "project-context.json",
    "backlog.json",
    "project-seed.md",
    "conventions.md",
    "architecture.mmd",
]

# Per-feature files under features/<name>/ — regenerable reports (stryker-report.json
# etc.) are intentionally excluded.
FEATURE_FILES = ["feature.json", "thinking.md", "research.md", "00-split.md"]

# Metadata file written by `collect` at the dest root (not a .project/ path).
MANIFEST_NAME = "state-manifest.json"

# --- Denylist (defense-in-depth, both directions) ----------------------------

# First path segment (relative to .project/) that must never travel.
DENY_TOP_SEGMENTS = {
    "session",
    "previews",
    "tmp",
    "cache",
    "screenshots",
    "wireframes",
    "playwright-runs",
    "security",
    "optimize",
    "plans",
}
# Exact .project/-relative paths that must never travel.
DENY_EXACT = {
    "auth-state.json",  # Playwright saved credentials — security
    "backlog.html",  # regenerated by the board server
}


def is_denied(rel: Path) -> bool:
    """True if a .project/-relative path is on the hard denylist."""
    parts = rel.parts
    if not parts:
        return True
    if parts[0] in DENY_TOP_SEGMENTS:
        return True
    if rel.as_posix() in DENY_EXACT:
        return True
    return False


def is_included(rel: Path) -> bool:
    """True if a .project/-relative path is part of the travelling manifest.

    Mirrors what `collect` enumerates, so `restore` can gate on the include-list
    (strictly stronger than the denylist) — a report or credential planted directly
    on the state branch is never restored.
    """
    parts = rel.parts
    if len(parts) == 1 and rel.as_posix() in TOP_LEVEL_FILES:
        return True
    if len(parts) == 3 and parts[0] == "features" and parts[2] in FEATURE_FILES:
        return True
    if parts[:1] == ("archive",):
        if rel.as_posix() == "archive/backlog-archive.json":
            return True
        if len(parts) == 2 and fnmatch(rel.name, "learnings-*.json"):
            return True
    if parts[:1] == ("thinking",) and len(parts) == 2 and rel.suffix == ".md":
        return True
    return False


# --- collect -----------------------------------------------------------------


def collect(project: Path, dest: Path) -> list[str]:
    src = project / ".project"
    if not src.is_dir():
        sys.exit(f"error: {src} does not exist")
    dest.mkdir(parents=True, exist_ok=True)

    copied: list[str] = []

    def take(rel: str) -> None:
        rel_path = Path(rel)
        if is_denied(rel_path):
            return
        s = src / rel_path
        if s.is_symlink():
            return  # symlinks never travel — copy2 would follow it outside .project/
        if not s.is_file():
            return
        d = dest / rel_path
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(s, d)
        copied.append(rel_path.as_posix())

    for name in TOP_LEVEL_FILES:
        take(name)

    features = src / "features"
    if features.is_dir():
        for feat in sorted(features.iterdir()):
            if not feat.is_dir() or feat.name == "archive":
                continue
            for fname in FEATURE_FILES:
                take(f"features/{feat.name}/{fname}")

    archive = src / "archive"
    if archive.is_dir():
        take("archive/backlog-archive.json")
        for learning in sorted(archive.glob("learnings-*.json")):
            take(f"archive/{learning.name}")

    thinking = src / "thinking"
    if thinking.is_dir():
        for md in sorted(thinking.glob("*.md")):
            take(f"thinking/{md.name}")

    manifest = {
        "schemaVersion": 1,
        "syncedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "sourceHost": socket.gethostname(),
        "files": copied,
    }
    (dest / MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return copied


# --- restore -----------------------------------------------------------------


def restore(src: Path, project: Path) -> list[str]:
    if not src.is_dir():
        sys.exit(f"error: {src} does not exist")
    dest = project / ".project"
    dest.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    for s in sorted(src.rglob("*")):
        if s.is_symlink():
            continue  # symlinks never travel — copy2 would follow it outside .project/
        if not s.is_file():
            continue
        rel = s.relative_to(src)
        if ".git" in rel.parts:
            continue  # src is a detached git worktree — skip its .git marker/dir
        if rel.name == MANIFEST_NAME and rel.parent == Path("."):
            continue  # branch metadata, not a .project/ file
        if not is_included(rel):
            continue  # include-list gate — drops denylisted + tampered/unknown files
        d = dest / rel
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(s, d)
        written.append(rel.as_posix())
    return written


# --- CLI ---------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_collect = sub.add_parser("collect", help="copy manifest subset out of .project/")
    p_collect.add_argument("--project", required=True, type=Path)
    p_collect.add_argument("--dest", required=True, type=Path)

    p_restore = sub.add_parser("restore", help="copy state files back into .project/")
    p_restore.add_argument("--src", required=True, type=Path)
    p_restore.add_argument("--project", required=True, type=Path)

    args = parser.parse_args()
    if args.cmd == "collect":
        files = collect(args.project.resolve(), args.dest.resolve())
        print(f"collected {len(files)} file(s)")
    elif args.cmd == "restore":
        files = restore(args.src.resolve(), args.project.resolve())
        print(f"restored {len(files)} file(s)")


if __name__ == "__main__":
    main()
